### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by mubashardev** [Bishwas-py/fiverr-scraping-api#2] opened 2022-01-09 13:59 UTC
File: "fiverr-scraping-api/src/fiverr_api.py", line 204, in profile_scrape
    user_area = profile.find('img', {'class': 'profile-pict-img'})
AttributeError: 'NoneType' object has no attribute 'find' 

Please fix it

**Comment by Bishwas-py** [comment] 2022-01-13 12:28
Thanks for the info, i'll fix it. Maybe you wanna fix it?

**Comment by Bishwas-py** [comment] 2022-01-13 12:33
> File: "fiverr-scraping-api/src/fiverr_api.py", line 204, in profile_scrape user_area = profile.find('img', {'class': 'profile-pict-img'}) AttributeError: 'NoneType' object has no attribute 'find'
> 
> Please fix it

Can you please explain the condition to create this error

**Comment by aminpow** [comment] 2023-01-21 18:04
I got the same error.

**Comment by aminpow** [comment] 2023-01-21 19:11
The problem is fiverr trying to check if you are a human and change the page code.

**Comment by wawj57751** [comment] 2023-06-05 17:27
I met the same error:
"AttributeError: 'NoneType' object has no attribute 'find'"

**Comment by wawj57751** [comment] 2023-06-05 20:05
> The problem is fiverr trying to check if you are a human and change the page code.

May I know if you fix it?

**Comment by Bishwas-py** [comment] 2023-08-31 13:31
> > @wawj57751 The problem is fiverr trying to check if you are a human and change the page code.
> 
> May I know if you fix it?

I'll be fixing it today.

**Comment by Bishwas-py** [comment] 2023-08-31 17:16
Please use the new code. The issue has been fixed, I believe. I am marking this as closed for now.

For scraping Fiverr profiles.
```python
from fiverr_api.scrapers import profile_scrape

# URL of the Fiverr profile you want to scrape
profile_url = "https://www.fiverr.com/some-seller"

# Scrape profile data
profile_data = profile_scrape(profile_url)

# Print the scraped profile data
print(profile_data)
```

[Read this](https://pypi.org/project/fiverr-api/#:~:text=(profile_data)-,Proxy%20Support,-You%20can%20use) to use proxies or change headers.

**Comment by Bishwas-py** [comment] 2023-08-31 17:17
Please use the new code. The issue has been fixed, I believe. I am marking this as closed for now.

For scraping Fiverr profiles.
```python
from fiverr_api.scrapers import profile_scrape

# URL of the Fiverr profile you want to scrape
profile_url = "https://www.fiverr.com/some-seller"

# Scrape profile data
profile_data = profile_scrape(profile_url)

# Print the scraped profile data
print(profile_data)
```

[Read this](https://pypi.org/project/fiverr-api/#:~:text=(profile_data)-,Proxy%20Support,-You%20can%20use) to use proxies or change headers.

**Closed as completed by Bishwas-py** 2023-08-31 17:17 UTC
